backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: carn-scot
    api_key: 576598791697792

collections:
  - name: page
    label: Page
    folder: 'src/pages/section-pages'
    create: true
    slug: '{{slug}}'
    sortable_fields: [order]
    fields:
      - label: Title
        name: title
        widget: string
      - label: Order
        name: order
        widget: number
      - label: Sections
        name: sections
        widget: list
        types:
          - label: Image
            name: image
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Subtitle,
                  name: subtitle,
                  widget: string,
                  required: false,
                }
          - label: Text
            name: text
            widget: object
            fields:
              - { label: Text, name: text, widget: markdown }
          # - label: Special
          #   name: special
          #   widget: object
          #   fields:
          #     - label: Section
          #       name: specialSection
          #       widget: select
          #       options: ['price-list', 'bench']
  # - name: 'special-section'
  #   label: 'Special Sections'
  #   files:
  #     - file: 'src/special-sections/price-list.md'
  #       label: 'Price List'
  #       name: 'price-list'
  #       fields:
  #         - { label: Title, name: title, widget: string }
  #         - { label: Text, name: text, widget: markdown }
  #     - file: 'src/special-sections/bench.md'
  #       label: 'Bench'
  #       name: 'bench'
  #       fields:
  #         - { label: Title, name: title, widget: string }
  #         - { label: Text, name: text, widget: markdown }
