backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: ekuwol
    api_key: 416452294223717

collections:     
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/gallery.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - label: Sections
            name: sections
            widget: list
            types:
              - label: Image
                name: image
                widget: object
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string, required: false}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: Text, name: text, widget: markdown }
      - file: "src/pages/info.md"
        label: "Info"
        name: "info"
        fields:
          - label: Sections
            name: sections
            widget: list
            types:
              - label: Image
                name: image
                widget: object
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string, required: false}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: Text, name: text, widget: markdown}
      - file: "src/pages/3d.md"
        label: "3D"
        name: "3d"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "3d-page"}
      - file: "src/pages/cook.md"
        label: "Cook"
        name: cook
        fields:
          - label: Sections
            name: sections
            widget: list
            types:
              - label: Image
                name: image
                widget: object
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string, required: false}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: Text, name: text, widget: markdown}

      - file: "src/pages/build.md"
        label: "Build"
        name: "build"
        fields:
          - label: Sections
            name: sections
            widget: list
            types:
              - label: Image
                name: image
                widget: object
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string, required: false}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: Text, name: text, widget: markdown}
